apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-s3-fastapi.fullname" . }}
  labels:
    app: {{ include "docker-s3-fastapi.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "docker-s3-fastapi.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "docker-s3-fastapi.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: aws-credentials